version: "3.9"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5434:5432"
    container_name: clean_arch_ddd
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_db
